version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:example123@db:5434/bookshelf_db
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: bookshelf_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
